application: nikmed-stats
version: 1
runtime: go
api_version: 3

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /images/github_logo\.png
  static_files: images/github_logo.png
  upload: images/github_logo.png
- url: /.*
  script: _go_app
